package CITSIM21_02.Vista;//
import CITSIM21_02.Enumeradores.TCategoria;
import CITSIM21_02.ModeloControlador.Aula;//
import CITSIM21_02.Enumeradores.TAula;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vista.GUIAulas.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import java.util.Scanner;

public class GUIAulas {

	public String pedirIdAula(){
		Scanner scan = new Scanner(System.in);
		System.out.println("   Introduzca el identificador del aula que desea agregar: ");
		return scan.nextLine();
	}
	public void rellenarAula(Aula aula) {
		Scanner scaner = new Scanner(System.in);
		System.out.println("   Introduce el centro de el aula:   ");
		aula.setCentro(scaner.nextLine());
		System.out.println("   Introduce el aforo:  ");
		aula.setAforo(Integer.valueOf(scaner.nextLine()));

		System.out.println("   Introduce el tipo de aula:   ");
		TAula cat = null;
		boolean salir;
		do{
			try{
				cat = TAula.valueOf(scaner.nextLine());
				salir=false;
			}catch (IllegalArgumentException e){
				System.out.println("   Error el tipo no es valido.\n   Vuelve a introducir un nuevo tipo(TEORIA, LABORATORIO, MIXTA):");
				salir=true;
			}
		} while(salir);
		aula.setTipoAula(cat);
	}
	public void show(){

	}
}
