package CITSIM21_02.Vista;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vista.GUIControladorAula.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//

import CITSIM21_02.ModeloControlador.Aula;
import CITSIM21_02.ModeloControlador.ContAula;

import java.util.Scanner;


public class GUIControladorAula {
	public int show(ContAula aulas) {
		int cont=0, op;
		System.out.println("   |LISTA DE AULAS DISPONIBLES|");
		for (Aula i: aulas.getListaAulas()) {
			cont++;
			System.out.println("   |"+cont+"|. Aula: "+i.getIdentificadorInterno()+", Centro: "+i.getCentro());
		}
		System.out.println("   |0|. Salir");
		do{
			System.out.println("\n   │Seleccione una opcion│-> ");
			Scanner scan = new Scanner(System.in);
			op = scan.nextInt();
		} while(op<0 || op>cont);
		return op;
	}
}

