package CITSIM21_02.Vista;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vista.GUIControladorUsuario.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import java.util.Scanner;

public class GUIControladorUsuario {
	public String introducirCorreo(){
		Scanner scan = new Scanner(System.in);
		System.out.println("   Introduzca su correo UPM: ");
		String correo = scan.next();
		return correo;
	}
}
