package CITSIM21_02.Vista;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vista.GUIObservador.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//



public class GUIObservador {

    public void show(){

    }
}
