package CITSIM21_02.Vista;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vista.GUIUsuario.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import java.util.Objects;
import java.util.Scanner;

import CITSIM21_02.Enumeradores.TCategoria;
import CITSIM21_02.ModeloControlador.Alumno;
import CITSIM21_02.ModeloControlador.PDI;
import CITSIM21_02.ModeloControlador.PAS;
import CITSIM21_02.ModeloControlador.Usuario;


public class GUIUsuario {
    public void rellenarPAS(PAS pas) {     this.rellenarUsuario(pas);
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su Codigo de Identificacion Personal PAS: ");
        pas.setCodigoPersonal(scan.nextInt());
        System.out.println("   Introduzca su anio de incorporacion: ");
        pas.setAnioDeIncorporacion(scan.nextInt());
    }
    public void rellenarPDI(PDI pdi) {
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su tipo de categoria: ");
        TCategoria cat=null;
        boolean salir;
        do{
            try{
                cat = TCategoria.valueOf(scan.nextLine());
                salir=false;
            }catch (IllegalArgumentException e){
                System.out.println("   Error la categoria no es valida.\n   Vuelve a introducir una nueva categoria(AYUDANTE, PROFESOR_AYUDANTE_DOCTOR, PROFESOR_CONTRATADO_DOCTOR, TITULAR, CATEDRATICO):");
                salir=true;
            }
        } while(salir);
        pdi.setCategoria(cat);
        System.out.println("   Introduzca su identificador de empleado: ");
        pdi.setIdentificadorEmpleado(scan.nextLine());
        this.rellenarUsuario(pdi);
    }
    public void rellenarAlumno(Alumno alumno) {
        this.rellenarUsuario(alumno);
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su numero de matricula:");
        alumno.setNumeroDeMatricula(scan.nextLine());
    }
    private void rellenarUsuario(Usuario user){

        Scanner scan = new Scanner(System.in);
        String ctr1, ctr2;
        do{
            System.out.println("   Introduzca una contraseña: ");
            ctr1 = scan.nextLine();
            System.out.println("   Vuelva a escribir la misma contraseña: ");
            ctr2 = scan.nextLine();
        } while(!Objects.equals(ctr1, ctr2));
        //System.out.println("  ->|LA CONTRASENIA ES: "+ctr1+" == "+ctr2+" |<-");
        user.setContrasenya(ctr1);
        System.out.println("   Introduzca su nombre: ");
        user.setNombre(scan.nextLine());
        System.out.println("   Introduzca su primer apellido: ");
        user.setPrimerApellido(scan.nextLine());
        System.out.println("   Introduzca su segundo apellido: ");
        user.setSegundoApellido(scan.nextLine());
        System.out.println("   Introduzca su DNI: ");
        user.setDNI(scan.nextLine());
    }
    public String pedirContrasenia(){
        Scanner scan = new Scanner(System.in);
        String ctr1, ctr2;
        do{
            System.out.println("   Introduzca una contrasenia: ");
            ctr1 = scan.nextLine();
            System.out.println("   Vuelva a escribir la misma contrasenia: ");
            ctr2 = scan.nextLine();
        } while(!Objects.equals(ctr1, ctr2));

        return ctr1;
    }
    public String pedirContraseniav2(){
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su contrasenia: ");
        return scan.nextLine();
    }
    public String pedirCorreo(){
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su correo: ");
        return scan.nextLine();
    }
    public String pedirNombre(){
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su nombre: ");
        return scan.nextLine();
    }
    public String pedirPrimerApellido(){
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su primer apellido: ");
        return scan.nextLine();
    }
    public String pedirSegundoApellido(){
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su segundo apellido: ");
        return scan.nextLine();
    }
    public String pedirDNI() {
        Scanner scan = new Scanner(System.in);
        System.out.println("   Introduzca su DNI: ");
        return scan.nextLine();
    }
}
