package CITSIM21_02.ModeloControlador;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.Alumno.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


public class Alumno extends Observador {
	private String numeroDeMatricula;

	public Alumno(String correo)
	{
		this.correo=correo;
	}

	public Alumno (String correo, String contrasenia, String nombre, String primerApellido,
				   String segundoApellido, String DNI, Perfil perfil, String numeroDeMatricula) {
		this.correo = correo;
		this.contrasenia = contrasenia;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.DNI = DNI;
		this.perfil = perfil;
		this.numeroDeMatricula = numeroDeMatricula;
	}

	public void setNumeroDeMatricula(String numeroDeMatricula) {
		this.numeroDeMatricula = numeroDeMatricula;
	}
	
	public String getNumeroDeMatricula() {
		return this.numeroDeMatricula;
	}
}
