package CITSIM21_02.ModeloControlador;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.Aula.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import CITSIM21_02.Enumeradores.TAula;

import java.util.ArrayList;

public class Aula implements IAula {
	private String centro; //
	private String identificadorInterno;
	private int aforo; //
	private TAula tipoAula; //
	public ArrayList<Observador> suscriptores;
	public PAS Pas;

	public Aula(String identificadorInterno, PAS pas) {
		this.identificadorInterno = identificadorInterno;
		this.Pas = pas;
		this.suscriptores= new ArrayList<>();
	}
	
	public Aula(String centro, String identificadorInterno, int aforo, TAula tipoAula) {
		this.centro = centro;
		this.identificadorInterno = identificadorInterno;
		this.aforo = aforo;
		this.tipoAula = tipoAula;
		this.suscriptores = new ArrayList<>();
	}
	public String getCentro() {
		return centro;
	}

	public String getIdentificadorInterno() {
		return identificadorInterno;
	}

	public int getAforo() {
		return aforo;
	}

	public PAS getPas() {
		return this.Pas;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}
	
	public void setIdentificadorInterno(String identificadorInterno) {
		this.identificadorInterno = identificadorInterno;
	}
	
	public void setAforo(int aforo) {
		this.aforo = aforo;
	}

	public void setPAS(PAS Pas)
	{
		this.Pas=Pas;
	}

	public void addObservador(Observador observador){
			this.suscriptores.add(observador);
	}
	public boolean claseLlena(){
		return suscriptores.size() >= aforo;
	}

	public void setTipoAula(TAula tipo)
	{
		this.tipoAula=tipo;
	}

}
