package CITSIM21_02.ModeloControlador;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.ContAula.java
//  @ Date : 13/05/2022
//  @ Author :
//
//


import java.util.ArrayList;
import java.util.Iterator;

public class ContAula implements IControladorAula {
	private ArrayList <Aula> listaAulas;

	public ContAula(){
		listaAulas = new ArrayList<>();
	}

	@Override
	public boolean agregarAula(Aula aula){
		if(!existeAula(aula.getIdentificadorInterno()))
		{
			listaAulas.add(aula);
			return true;
		}
		else
			return false;
	}

	public boolean eliminarAula(Aula aula) {
		if(listaAulas.isEmpty())
			return false;
		else if(!listaAulas.contains(aula))
			return false;
		else{
			listaAulas.remove(aula);
			return true;
		}
	}

	public boolean existeAula(String id){
		boolean existe = false;
		Iterator<Aula> i= listaAulas.iterator();

		while(i.hasNext() && !existe)
		{
			if(id.equals(i.next().getIdentificadorInterno()))
				existe=true;
		}
		return existe;
	}
	public ArrayList<Aula> getListaAulas(){
		return this.listaAulas;
	}

	public Aula getAulaId(String id)
	{
		Aula aula = null;
		for(Aula i: listaAulas)
			if(i.getIdentificadorInterno().equals(id))
				aula=i;

		return aula;
	}

}
