package CITSIM21_02.ModeloControlador;//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.IAula.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//




public interface IAula {
}
