package CITSIM21_02.ModeloControlador;//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.IControladorAula.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//




public interface IControladorAula {
	boolean agregarAula(Aula aula);

	boolean eliminarAula(Aula aula);
	
	boolean existeAula(String id);
}
