package CITSIM21_02.ModeloControlador;//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.IControladorUsuario.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


//import CITSIM21_02.ModeloControlador.Usuario;

import servidor.UPMUsers;

public interface IControladorUsuario {
	UPMUsers AltaUsuario(String correo);
	PAS crearPAS(String correo);
	Alumno crearAlumno(String correo);
	boolean loguearMenu(String correo, String ctr, String tipo);

	boolean agregarUsuario(Usuario usuario);
}
