package CITSIM21_02.ModeloControlador;//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.IObservador.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import CITSIM21_02.ModeloControlador.Aula;

public interface IObservador {
	boolean suscribirse(Aula aula);
}
