package CITSIM21_02.ModeloControlador;//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.IUsuario.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//




public interface IUsuario {
	Boolean login(String nick, String contrasenia, String ns);
}
