package CITSIM21_02.ModeloControlador;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.PAS.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.Iterator;
import CITSIM21_02.ModeloControlador.ControladorUsuarios;
public class PAS extends Usuario {
	private int codigoPersonal;
	private int anioDeIncorporacion;
	private ArrayList<Aula> aulas;

	public PAS(String correo)
	{
		this.correo=correo;
		aulas= new ArrayList<>();
	}

	public PAS(int codigoPersonal, int anioDeIncorporacion, String correo, String contrasenia, String nombre, String primerApellido,
			   String segundoApellido, String DNI, Perfil perfil){
		this.correo = correo;
		this.contrasenia = contrasenia;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.DNI = DNI;
		this.perfil = perfil;
		this.codigoPersonal = codigoPersonal;
		this.anioDeIncorporacion = anioDeIncorporacion;
		aulas = new ArrayList<>();
	}

	public boolean addAula(Aula aula){
		boolean existe = false;
		/*
		Iterator<Aula> i= aulas.iterator();

		while(i.hasNext() && !existe)
		{
			if(aula.getIdentificadorInterno().equals(i.next().getIdentificadorInterno()))
					existe=true;
		}
*/
		for(Aula amigo: aulas)
		{
			if(aula.getIdentificadorInterno().equals(amigo.getIdentificadorInterno()))
				existe=true;
		}
		if(!existe)
		{
			aulas.add(aula);
			return true;
		}
		else
			return false;
	}

	public boolean removeAula(Aula aula){
		boolean existe = false;
		Iterator <Aula> i = aulas.iterator();
		while(i.hasNext() && !existe)
			if(i.next().getIdentificadorInterno().equals(aula.getIdentificadorInterno()))
				existe = true;
		if(existe)
			aulas.remove(aula);
		return existe;
	}

	public Aula darAltaAula(String id, PAS pas){
		Aula aula = new Aula(id, pas);
		return aula;
	}

	public ArrayList<Aula> getAulas() {
		return aulas;
	}

	public int getCodigoPersonal() {
		return codigoPersonal;
	}

	
	public int getAnioDeIncorporacion() {
		return anioDeIncorporacion;
	}
	
	public void setCodigoPersonal(int codigoPersonal) {
		this.codigoPersonal = codigoPersonal;
	}
	
	public void setAnioDeIncorporacion(int anioDeIncorporacion) {
		this.anioDeIncorporacion = anioDeIncorporacion;
	}
}
