package CITSIM21_02.ModeloControlador;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModeloControlador.Usuario.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//


import servidor.Autenticacion;

import java.util.Objects;
import java.util.Scanner;

public abstract class Usuario implements IUsuario {
	protected String correo;
	protected String contrasenia;
	protected String nombre;
	protected String primerApellido;
	protected String segundoApellido;
	protected String DNI;
	protected Perfil perfil;
	private Scanner scanner = new Scanner(System.in);

	public Boolean login(String nombre, String constrasenia, String correo) {
		boolean acceder = false;
		int opcion;
		System.out.println("que quiere hacer:\n\t1.logearse\n\t0.Olvide contrasenia");
		opcion = Integer.parseInt(scanner.next());

		if(opcion == 1) {
			int cont = 0;
			while (cont < 3 && !acceder) {
				Autenticacion autenticacion = new Autenticacion();
				if(nombre.equals(this.nombre) && constrasenia.equals(this.contrasenia) && correo.equals(this.correo)
																			&& autenticacion.existeCuentaUPM(correo))
					acceder = true;
				else{
					cont ++;
					System.out.println("introduzca los datos de nuevo:");
					nombre = scanner.next();
					constrasenia = scanner.next();
					correo = scanner.next();

				}

			}
			if (!acceder) {
				recuperarContrasenya();
				return false;
			}

		}
		else{
			recuperarContrasenya();
			acceder = false;
		}

		return acceder;
	}

	private void recuperarContrasenya() {
		Scanner scanner= new Scanner(System.in);
		String con;
		boolean res= false;

		System.out.println("Demasiado intentos fallidos, iniciando proceso de recuperado de contraseña...\n" +
							"Introduce tu correo seguido de tu DNI: ");

		if(scanner.next().equals(this.getCorreo()) && scanner.next().equals(this.getDNI()))
		{
			do{
				System.out.println("Introduce una nueva contraseña: ");
				con= scanner.next();
				System.out.println("Confirma la nueva contraseña: ");
			} while(!Objects.equals(con, scanner.next()));
			res=true;
		}

		if(res)
			System.out.println("Contraseña cambiada con éxito.");
		else
			System.out.println("Error con los datos introducidos, saliendo del sistema...");
	}
	
	public String getCorreo() {
		return correo;
	}
	
	public String getContrasenya() {
		return contrasenia;
	}
	
	public String getNombre() {
		return nombre;
	}

	public String getPrimerApellido() {
		return primerApellido;
	}
	
	public String getSegundoApellido() {
		return segundoApellido;
	}
	
	public String getDNI() {
		return DNI;
	}

	public Perfil getPerfil() {
		return perfil;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public void setContrasenya(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}
	
	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}
	
	public void setDNI(String DNI) {
		this.DNI = DNI;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}
}
