package CITSIM21_02.Persistencia;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persistencia.PersistenciaAlumno.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//




public class PersistenciaAlumno implements IPersistenciaAlumno {
}
