package CITSIM21_02.Persistencia;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persistencia.PersistenciaAula.java
//  @ Date : 13/05/2022
//  @ Author : 
//
//




public class PersistenciaAula implements IPersistenciaAula {
}
